name: life_engine
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pygame=2.5.2
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - pip
  - pip:
    - opensimplex==0.4.5 